# Generated by Django 5.1.4 on 2026-03-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ridesmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("accepted", "Accepted"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="started",
                max_length=20,
            ),
        ),
    ]
