# Generated by Django 6.0.3 on 2026-03-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_alter_ridesmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ridesmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("accepted", "Accepted"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
    ]
