# Generated by Django 6.0.3 on 2026-03-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0003_alter_ridesmodel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridesmodel",
            name="current_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
